### PR TITLE
Update DigiByte Seed Nodes

### PR DESCRIPTION
**Pull request by JaredTate**
Signed-off-by: Jared Tate <13957390+JaredTate@users.noreply.github.com>

After looking through the hardcoded seed nodes for DigiByte-Core as well as digibytewallet-core for the mobile wallets both codebases need to be updated with more seeds to help fix connection issues now being experienced, especially the light wallets.

Running a DGB core seed node is simple. You just need to have a URL (example: seed.digibyte.io) and a DigiByte Core full node of the latest version that's running 24/7 at that address. It's also helpful to add "maxconnections=800" or any higher number to allow more than 8 peers at a time in the digibyte.conf file.

If you are interested in running a full-time seed node for the next few years to help the network out please mention it in a comment below with the URL. Let me know if you see any issues with seeds listed below.

These seeds are working great: 

```
static const char *BRMainNetDNSSeeds[] = {
        "seed.digibyte.io", // Jared Tate
        "seed.digihash.co", // Jared Tate
        "dnsseed.esotericizm.site", // DigiContributor
        "seed.digiexplorer.info", // DigiByte Foundation
        "seed.digiassets.net", // DigiByte Foundation
        "digibyteblockexplorer.com", // DigiByte Block Explorer
        "dgb1.trezor.io", // Trezor
        "seed2.digibyte.io", // Jared Tate
        "seed3.digibyte.io", // Jared Tate
        "seed.digibyteblockchain.com", // JS555
        "seed.digibyte.host", // SashaD
        "seed.digibytefoundation.org", // DigiByte Foundation
        "seed.digibyte.org", // Website collective
        "seed.digibyteservers.io", NULL // ChillingSilence
};

### CODE REVIEW

**Review by SmartArray — APPROVED** [review]
ACK

**Comment by Quakeitup** [comment]
dgb.quakeguy.com

**Review by gto90 — APPROVED** [review]
ACK

**Comment by gto90** [comment]
@JaredTate , did you want to add the seed from @Quakeitup ?

**Comment by ChillingSilence** [comment]
No, that's not a seed @gto90 , it's Jared being confused asking people to run a node.
Most of this list from @JaredTate is wrong
Do *not* push a release with this list. Prune all the stale dnsseeds. If they're not responding correctly on UDP Port 53 (Or have not indicated they will be running a dnsseed), then they should *not* be added as that will only cause further problems.

**Comment by mtaipe** [comment]
The [policy](https://github.com/DigiByte-Core/digibyte/blob/develop/doc/dnsseed-policy.md) says that the TTL must be less than a minute, there are some that are returning a higher TTL. Also, in that list we have some seeds that are not replying.
image

**Comment by mtaipe** [comment]
This are seeds nodes, not A records pointing to a Digibyte node, so I would suggest to remove those entries and only use these dnsseeds that are working properly:
seed.digibyte.org
seed.digibyteservers.io
seed.digibyte.io
dnsseed.lifehash.com

With only those 4, about 70 unique nodes will be discoverable, those 14 entires shown in the first post returns less.
image

Also these two files must use the same list to make troubleshooting  easier:
[BRChainParams.h](https://github.com/DigiByte-Core/digibytewallet-core/blob/7331a22bfb1fdde260aa35c006893c63bda9a950/BRChainParams.h#L49) and [chainparams.cpp](https://github.com/DigiByte-Core/digibyte/blob/2bd62c03b686de69bce8bb3e1756782531127644/src/chainparams.cpp#L220)

**Comment by guywriz** [comment]
I had got a Smart contract with my DigiAssets Already from my friend on YouTube

**Pull request merged**
