### PR TITLE
Updates seed and fix bug for android release branch

### PR DESCRIPTION
**Pull request by digicontributer**

### CODE REVIEW

**Review by gto90 — APPROVED** [review]
cACK

**Comment by ChillingSilence** [comment]
Most of those aren't dnsseeds and the list should 100% be pruned prior to any kind of release.
Test them with nslookup first, the response should come on UDP Port 53.

Releasing with these will only cause more issues with stale dnsseeds.

Only 3/10 of those are actually valid and responding correctly right now.

**Comment by digicontributer** [comment]
Hostnames are looked up using C's netdb.h which for DNS seeds will return a list of IP addresses.

For nodes with hostnames, the hostnames will be resolved to a single IP or null. 

Shouldn't cause many if any issues as long as there's an IP somewhere there to connect to.

**Comment by ChillingSilence** [comment]
The current wallet was spending time (so I'm told by someone who ran it through Wireshark and a profiler) busy looking up Hashdragon etc which caused delays. How much, I can't say, I don't know, but why would we add in nodes that don't work to begin with, and likely never will work ? Why not just... Not add them? And instead, only put in one's that do work, or where the likes of individuals have stated that they want to specifically run a dnsseed?

Again I'm aware I submitted wrong entries originally myself, but they too should have been picked up with more than a cACK before being merged.

**Comment by digicontributer** [comment]
There was an issue on android (probably wouldn't have affected iOS) during the initial sync where it would pause for 60 seconds while checking the URL for one of the explorers you had hosted, This then cycled to the next explorer you were hosting and locked up again for 60 seconds, I'm not sure if this is the issue you mention above but if so then it has been fixed.

When you say that they "don't work" what do you mean? They still resolve to IP addresses that have a node hosted at that IP (or did when I checked) address they just are NOT dnsseeds. I tested before I submitted this PR and was able to grab connections to peers fairly quickly.

**Comment by ChillingSilence** [comment]
Well we have seed2.digibyte.io // seed3.digibyte.io in there currently, but yet, we had countless people having issues with the wallet not launching due to there being no dnsseeds and nothing was resolving? I hadn't been on Telegram or Twitter and yet we had two weeks worth of people saying there were issues, that I only came to know about after js555 contacted me.

Re-launch dnsseed on seed.digibyteservers.io (which hadn't auto started after the virtual server got rebooted) and immediately not just my wallet but every single other person who *had* issues that had contacted me began working again. That was a week or two ago now? Are there other issues that have persisted since?

As for the Explorers, nobody was around to help with fixing issues with Insight (Yoshi and Barry had a brief look but were unable to ascertain the root of the issue), so it was replaced on DigiExplorer. To my knowledge it's still working?

So having multiple entries, on the same domain, controlled by the same individual, is pretty pointless. What I suggested to js555 was having unique dnsseeds, in geographically diverse locations, with different hosting providers, provided by different people, using different domains of their own. That would provide the proper redundancy needed, not to mention it's $5/month for a basic server that can do the dns responses as opposed to $$$ needed for something with 8GB+ RAM, a beefy CPU and a ton of data to sync the blockchain to.
If this pull request is to add dnsseeds to fix reliability issues, why not have actual dnsseeds (nice to see LifeHashs in the list and working) and make them reliably work into the future?

**Comment by digicontributer** [comment]
> Re-launch dnsseed on seed.digibyteservers.io (which hadn't auto started after the virtual server got rebooted) and immediately not just my wallet but every single other person who had issues that had contacted me began working again. That was a week or two ago now? Are there other issues that have persisted since?

Awesome so it sounds like as long as we have DNS seeds on the list (which again you acknowledge we do) then we should be sweet right?

**Pull request merged**
